name: hunger_meal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  data:
    path: ../data

  domain:
    path: ../domain

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0

  photo_view: ^0.14.0

  grouped_list: ^5.1.2
  flutter_slidable: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.0
  loading_animations: ^2.2.0
  dotted_border: any
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.1

  rxdart: ^0.27.7
  dio: ^5.3.3
  tuple: ^2.0.2
  http: ^1.1.0
  basic_utils: ^5.6.1
  json_annotation: ^4.8.1
  #dio_http_cache: ^0.3.0

  intl: ^0.18.0
  path_provider: ^2.1.1

  pin_code_fields: ^8.0.1
  #cached_network_image: ^3.2.3
  phone_number_text_field: ^0.0.7

  get_it: ^7.6.4
  injectable: ^2.3.0
  auto_route: ^7.8.3
  equatable: ^2.0.5
  url_launcher: ^6.1.14

  huawei_map: ^6.11.0+304
  google_maps_flutter: ^2.5.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1

  geolocator: ^10.1.0
  geocoding: ^2.1.0

  chewie: ^1.7.1
  video_player: ^2.7.2
  dots_indicator: ^3.0.0

dev_dependencies:

  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  auto_route_generator: any
  injectable_generator: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/icon_payment/
    - assets/images/
    - assets/profile/

  fonts:
    - family: FuturaLT
      fonts:
        - asset: fonts/FuturaLT-Light.ttf
          weight: 300
        - asset: fonts/FuturaLT-Book.ttf
          weight: 500
        - asset: fonts/FuturaLT-Heavy.ttf
          weight: 600
        - asset: fonts/FuturaLT-Bold.ttf
          weight: 700
