name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  collection: ^1.17.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
